// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBank.Models;

namespace MovieBank.Migrations
{
    [DbContext(typeof(MovieBankContext))]
    partial class MovieBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieBank.Models.MovieItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Director");

                    b.Property<string>("Genre");

                    b.Property<string>("Height");

                    b.Property<int>("Rating");

                    b.Property<string>("Title");

                    b.Property<string>("UID");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Url");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.ToTable("MovieItem");
                });

            modelBuilder.Entity("MovieBank.Models.ReviewItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.Property<int>("RevRefID");

                    b.Property<string>("Review");

                    b.Property<string>("UID");

                    b.Property<string>("Uploaded");

                    b.HasKey("Id");

                    b.HasIndex("RevRefID");

                    b.ToTable("ReviewItem");
                });

            modelBuilder.Entity("MovieBank.Models.ReviewItem", b =>
                {
                    b.HasOne("MovieBank.Models.MovieItem")
                        .WithMany("Reviews")
                        .HasForeignKey("RevRefID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
