// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBankAPI.Models;

namespace MovieBankAPI.Migrations
{
    [DbContext(typeof(MovieBankAPIContext))]
    [Migration("20181121103931_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("MovieBankAPI.Models.MovieItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Director");

                    b.Property<string>("Genre");

                    b.Property<string>("Height");

                    b.Property<int>("Rating");

                    b.Property<string>("Title");

                    b.Property<int>("UID");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Url");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.ToTable("MovieItem");
                });

            modelBuilder.Entity("MovieBankAPI.Models.ReviewItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.Property<int>("RevRefID");

                    b.Property<string>("Review");

                    b.Property<int>("UID");

                    b.Property<string>("Uploaded");

                    b.HasKey("Id");

                    b.HasIndex("RevRefID");

                    b.ToTable("ReviewItem");
                });

            modelBuilder.Entity("MovieBankAPI.Models.ReviewItem", b =>
                {
                    b.HasOne("MovieBankAPI.Models.MovieItem")
                        .WithMany("Reviews")
                        .HasForeignKey("RevRefID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
