// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieAPI.Models;

namespace MovieAPI.Migrations
{
    [DbContext(typeof(MovieAPIContext))]
    partial class MovieAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("MovieAPI.Models.MovieItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Director");

                    b.Property<string>("Genre");

                    b.Property<string>("Height");

                    b.Property<double>("Rating");

                    b.Property<string>("Title");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Url");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.ToTable("MovieItem");
                });

            modelBuilder.Entity("MovieAPI.Models.ReviewItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MovieItemId");

                    b.Property<string>("Name");

                    b.Property<double>("Rating");

                    b.Property<string>("Review");

                    b.Property<string>("Uploaded");

                    b.HasKey("Id");

                    b.HasIndex("MovieItemId");

                    b.ToTable("ReviewItem");
                });

            modelBuilder.Entity("MovieAPI.Models.ReviewItem", b =>
                {
                    b.HasOne("MovieAPI.Models.MovieItem")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
